resources:
- name: terraform-provider-google
  type: git
  source:
    uri: https://github.com/terraform-providers/terraform-provider-google.git
    branch: master
- name: ci
  type: git
  source:
    uri: https://github.com/rosbo/terraform-provider-google-ci.git
    branch: master

jobs:
- name: build
  plan:
  - get: terraform-provider-google
    trigger: true
  - get: ci
    trigger: true
  - task: run-build
    file: ci/build/task.yml

- name: unit-tests
  plan:
    - aggregate:
      - get: terraform-provider-google
        passed: [build]
      - get: ci
        passed: [build]
    - task: run-unit-tests
      file: ci/unit-tests/task.yml

- name: acceptance-tests
  plan:
    - aggregate:
      - get: terraform-provider-google
        passed: [unit-tests]
      - get: ci
        passed: [unit-tests]
    - task: run-acceptance-tests
      file: ci/acceptance-tests/task.yml