# List of resources
resources:
- name: terraform-provider-google
  type: git
  source:
    uri: https://github.com/terraform-providers/terraform-provider-google.git
    branch: master
    paths:
    - google/*

- name: terraform-ci
  type: git
  source:
    uri: https://github.com/selmanj/terraform-provider-google-ci.git
    branch: master

jobs:
- name: acceptance-tests
  plan:
  - get: terraform-provider-google
    resource: terraform-provider-google
  - get: ci
    resource: terraform-ci

  - task: run-acceptance-tests
    config:
      platform: linux
      params:
        google_json_account: ((terraform-ci-acc-tests-json))
      inputs:
      - name: terraform-provider-google
      - name: ci
      image_resource:
        type: docker-image
        source: {repository: golang}
      run:
        path: ci/run-acceptance-tests.sh
