resources:
- name: terraform-provider-google
  type: git
  source:
    uri: https://github.com/terraform-providers/terraform-provider-google.git
    branch: master
- name: one-off-terraform-provider-google
  type: git
  source:
    uri: https://github.com/terraform-providers/terraform-provider-google.git
    branch: one-off
- name: ci
  type: git
  source:
    uri: https://github.com/rosbo/terraform-provider-google-ci.git
    branch: master

jobs:
- name: build
  plan:
    - aggregate:
      - get: terraform-provider-google
        trigger: true
      - get: ci
    - task: run-build
      file: ci/build/task.yml

- name: unit-tests
  plan:
    - aggregate:
      - get: terraform-provider-google
        trigger: true
        passed: [build]
      - get: ci
        passed: [build]
    - task: run-unit-tests
      file: ci/unit-tests/task.yml

- name: acceptance-tests
  serial_groups: ["gcp"]
  plan:
    - aggregate:
      - get: terraform-provider-google
        trigger: true
        passed: [unit-tests]
      - get: ci
        passed: [unit-tests]
    - task: run-acceptance-tests
      file: ci/acceptance-tests/task.yml

- name: one-off-build
  plan:
    - aggregate:
      - get: terraform-provider-google
        resource: one-off-terraform-provider-google
        version: every
        trigger: true
      - get: ci
        trigger: true
    - task: run-build
      file: ci/build/task.yml

- name: one-off-unit-tests
  plan:
    - aggregate:
      - get: terraform-provider-google
        resource: one-off-terraform-provider-google
        version: every
        trigger: true
        passed: [one-off-build]
      - get: ci
        trigger: true
        passed: [one-off-build]
    - task: run-unit-tests
      file: ci/unit-tests/task.yml

- name: one-off-acceptance-tests
  serial_groups: ["gcp"]
  plan:
    - aggregate:
      - get: terraform-provider-google
        resource: one-off-terraform-provider-google
        version: every
        trigger: true
        passed: [one-off-unit-tests]
      - get: ci
        trigger: true
        passed: [one-off-unit-tests]
    - task: run-acceptance-tests
      file: ci/acceptance-tests/task.yml